PITCH_C = 0
PITCH_Cis = 1
PITCH_D = 2
PITCH_Dis = 3
PITCH_E = 4
PITCH_F = 5
PITCH_Fis = 6
PITCH_G = 7
PITCH_Gis = 8
PITCH_A = 9
PITCH_Ais = 10
PITCH_B = 11
SILENCE = 12

N_PITCHES = 12
N_OCTAVES = 10
DEFAULT_TEMPO = 160

DEF_NUMBER_NOTES = 100
DEF_TICK_STEP_SIZE = 30
MAXIMUM_SEQUENCE_LENGTH = 30
